server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: internal-workflow
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/internal_workflow}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Imran@812}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: info
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
